### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [babyboomer53/TeaCozy#4]
[Exceeds Expectations] Brilliant!

**Great work with:**
- easy to navigate project structure
- div usage
- informative class and id names
- relative links to images and stylesheet
- flexbox usage
- comments usage
- readme file
- git commits 
- links to google maps
- explanation of style choices
- meeting the spec and making it your own

**Improve on:**
- indentation
- alt tag usage
- images with captions

**Future challenges to try:**
- responsive design using media queries

In terms of comments, you wrote a lot of the decisions you made in your comments. However, it is better to write that information in the readme file. 

Overall, fantastic! You are on 🔥! 👍

**Comment by babyboomer53** [comment]
I made most if not all of the corrections while modifying the project to replace tables with flex boxes. To do so, I created a new branch so that the version I knew to be working would not be jeopardized. Once I was satisfied that the new version was working correctly, I merged it with the master branch.
